name: Check licenses

on:
  pull_request:

permissions:
  packages: read

jobs:
  check-licenses:
    runs-on: ubuntu-22.04
    env:
      LICENSES: "'Apache-2.0' 'GPL-3.0-only' 'GPL-3.0-or-later WITH Classpath-exception-2.0'"
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@2d7d9f7ff5b310f983d059b68785b3c74d8b8edd # v4.0.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@paritytech"
        
      - name: Check the licenses in Polkadot
        run: |
          shopt -s globstar
          npx @paritytech/license-scanner scan \
            --ensure-licenses ${{ env.LICENSES }} \
            -- ./polkadot/**/*.rs

      - name: Check the licenses in Cumulus
        run: |
          shopt -s globstar
          npx @paritytech/license-scanner scan \
            --ensure-licenses ${{ env.LICENSES }} \
            --exclude ./cumulus/parachain-template \
            -- ./cumulus/**/*.rs

      - name: Check the licenses in Substrate
        run: |
          shopt -s globstar
          npx @paritytech/license-scanner scan \
            --ensure-licenses ${{ env.LICENSES }} \
            --exclude ./substrate/bin/node-template \
            -- ./substrate/**/*.rs
