name: Rustfmt check

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quick_check:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    container:
      image: paritytech/ci-unified:bullseye-1.70.0-2023-05-23-v20230706
    steps:
      - uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.0.0

      - name: Cargo fmt
        run: cargo +nightly fmt --all -- --check
